import Head from "next/head";
import React, { useEffect, useState } from "react";
import { SidebarFreud } from "~/SidebarFreud";
import { VectorStoreSettings } from "~/components/VectorStoreSettings";
import { type Message } from "~/interfaces/message";

import { env } from "~/env.mjs";
import Header from "~/components/Header";
import Chat from "~/components/Chat";
import SelectCategories from "~/components/SelectCategories";
import { api } from "~/utils/api";

export type Categories = { [key: string]: { active: boolean } }

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [showSettings, setShowSettings] = useState<boolean>(false);
  const [categories, setCategories] = useState<Categories>({});

  const fetchedCategories = api.weaviate.listSchemas.useMutation({
    onSuccess: (data) => {
      console.log("data", data)
      data?.classes?.map((item) => {
        let name: string;
        if (!item.class) {
          name = "Kategori uten navn";
        } else {
          name = item.class
        }

        setCategories(prevState => ({
          ...prevState,
          [name]: { active: false }
        }));

      })
    }
  });

  useEffect(() => {
    fetchedCategories.mutate();
  }, [])



  return (
    <>
      <Head>
        <title>Freud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/sigmund_freud_avatar.png" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-between bg-beige100 px-8 pb-8`}
      >
        {env.NEXT_PUBLIC_NODE_ENV == "development" && (
          <SidebarFreud
            showSettings={showSettings}
            setShowSettings={setShowSettings}
          >
            <VectorStoreSettings />
          </SidebarFreud>
        )}
        {/* get content in center at start */}
        <div />
        <div />
        <Header chatStarted={messages.length > 0} />
        <SelectCategories categories={categories} myfunc={setCategories} />
        <Chat messages={messages} setMessages={setMessages} categories={categories} />
      </main>
    </>
  );
}
