import Head from "next/head";
import React, { useState } from "react";
import { SidebarFreud } from "~/SidebarFreud";
import { VectorStoreSettings } from "~/components/VectorStoreSettings";
import { type Message } from "~/interfaces/message";

import { env } from "~/env.mjs";
import Header from "~/components/Header";
import Chat from "~/components/Chat";

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [showSettings, setShowSettings] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Freud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/sigmund_freud_avatar.png" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-between bg-beige100 px-8 pb-8`}
      >
        {env.NEXT_PUBLIC_NODE_ENV == "development" && (
          <SidebarFreud
            showSettings={showSettings}
            setShowSettings={setShowSettings}
          >
            <VectorStoreSettings />
          </SidebarFreud>
        )}
        {/* get content in center at start */}
        <div />
        <div />
        <Header chatStarted={messages.length > 0} />
        <Chat messages={messages} setMessages={setMessages} />
      </main>
    </>
  );
}
